apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: gitops-repo
  namespace: flux-system
stringData:
  identity: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKAIBAAKCAgEAt9A2LiaA7BOW1Sucta2aJ5RH0fz0LDgL5G+JR5wRQh9FCWhf
    vuvZ4rwtc392BDFLlEZdfQWZvS9DBr8GgqTEzarksnZpvFYyusznT99grspkAOs2
    qDFlOhpMCVOHRjXVFi0gKXjnIJ9mKrlJzX3XwsM/TOSNhIq/HFvN7KJNmnEDxH9j
    V35jUZG2KOzamXfs3uK7tGu30ZRBYcyN4inFFjkB4sxb4ejoU2AywcJwPZ7nMCRD
    2GvAXXiHEL5v4FRlvT4RvxPyjfc8cwMyuAMjfpuIGs/JCWR6a3JO7xsA74Deno1T
    i58Ha+2UGwWt8ZvI5LtovHuzwH5Vfwt/wZwfT7BRgGeSEnqwalmI4nar+S+Vh1Es
    ExOI/7LyvdIxAPYgQSIB4ZXNU2fo1karjs5zkz+yqxPcYRRv54jk7nRH+jx1KqP0
    +UCUpGLawMiCG/suVG1tZvBHzR+QtUoRaRXovSC2H1DrILKBQQq9FKgF1F4o5JnK
    byezSx6uQIHp1irdClIBozoB31jqKtd9+M9psuNOuceC0dEiYMGZCRvA+lOD/jNi
    D40YRgLMFJmH1uOJp9aPEe+Zthw7Rzj7kJ0CZ74mmm50DKSPP8IQv0g88KRW/bK8
    9cB36tN0BQyd45MYsiXc/93I6HbvGhajJq+cBlvj0QP1Bqxm97cawsKWV8kCAwEA
    AQKCAgBLz85o3myR8cpmBWTO8dkAtgGhNCkpC7yr7Oy74jyj/u2kYa4Luo7VGzPL
    zShJtmMrtpHcfLDZ/GIyqBrxSy/4e6Fzka8uhIbL0LMemEzyCnuQfXK/kA/mFO6D
    cjX62T0Xtmjrcfgx1kx3FpC/9kVFCO5UsndD0U3dTmfyT0aeijo5kyjP70rbW7O7
    0WSfo3zIuM8eLMdV40XMJmfmfb/R2JVUi2DiHgOkT6rfi2hrodxMWMi6vEZMxuc+
    Gq1d4rFLigwbuQhzUSNXdFw41OKQ12kdVdHe09hB9JVlvMd4ALjQwA1TKrYO56AM
    PR1u5wfGfx1Fj+elXvW4Pm/k1JV8v0zhct6C47QJ6CCkUFigcE3lw/MlzFWDtTvQ
    9cqZFB1OB5Bs0CNUUWBM4iXMRUU1MYoGH3JymEtCgyX0rTLibBBEbls358DMHv4z
    ASpbPPTy4myeuuJbNia1bZP/p6Aqtz8Krgz1/7448EE5MEp1vbS/bUPlOg+b8sET
    P6MndbwWy/sK6aC9R/Stu88cSjlfHwgwyAV6TmtzBOjVlfP+d9P2XJuBy3kX4KH9
    zecPowiu/ZZmMleB76dO5Gj/ig1SqxZIlhN43dsS0S3cl+lCUBsCUsEryrtPF3i3
    ANsXzE3GMRXcnfqWKnXtiWC4GTbRZa6d4LX7bb3cbxWSPr+OAQKCAQEA5YBSqFTp
    yoBescgFqMO+kQW7FyBn/TIK8AmO9gwYW9a3DW6i/uli/dJe3jrktlA4Y92sdENN
    VOSWMnK8bdSjvTa7pD1lx5PFNQsHxQUFksPD6maLAbBMKSt35xsjPOlLS19g2V15
    xGC22nLWEIVTQQT1XJN8lmBotJILXiQEJ1xz1en0Tb8wEGJo8g2YO03P8snVZApU
    I3LsV9vAr6Xau32k9ZsoLtSyvJQdL+GlphGQ28SiwOwFx5l7aCSUUjDE3oQY3CLD
    gH6aYQ5UL+ppXCz+VL3L9pATOJPlH8JJ5uHGSV715mibcPESyf1rPNsNtTQ3/U+y
    N8MuvIWgoN9OqQKCAQEAzQlt2U2o3bv0R4Xy8CUtN/gXXuq2Ngk3095O/TiP5BTS
    mcoT6G8Z3x++2kZJkzpFLp2XvGc4vBkg0tVNGeh1lzfC59qFe/1UslN2uRJnIDoT
    H01jS65YyCi0ldhteko5X4Dj9i72AYpcoPlUdJOPQwncFrZO7cpQKReCjHEjvViA
    b4kZWeZL3puESuJGKS9dbt5DCg/3YZkW80JTg8mON2EKaym9KAZcdX+23BGxLERN
    Za+OyhSsYTKaGI4PQxnzG47Y91WOwj/herAxkhA/oXGYCo/4ESxzlZLWUi1dyLnm
    ZdvN4lH/lDUS4SZLxHEMr9qLEneG62S08sJuB2gUIQKCAQEAr404LSE+8LK/PLin
    c4+/7sj2cttMEEa+TRzSqW1ZGK8muPSfY+R833GTNeTQ3JCCggmoCAsPVVfBeHeB
    oXXdhjge0qRQfZiQamG0oMWVnM14yI2F2VXU/E0O285LZyWBffdIaxzwrwHX/UOI
    cXy60WqMkTMUQyceELoCThG4x68VwFTEltAfYPkWE8nIX9zGq44uV+b6s18OYKpt
    Oy7gITkb/O+hjikPS+b0aJLvlheruiAw6ufgB+1kk6YfertpbFiZd5Jz/49YYdOH
    HFvwGh0kswe3xDQzL70Zr/B7fUvI1Ij6CjSMaplNaQsbg6KAWtLF3VOgHL2Fu5lv
    5H7MeQKCAQAEKGnK21FOVc5pWOUJS6e0F9rZeOcDB4LTUBHH/sqkNGvk5H0s3Hvo
    02r6YCyDyM24WUfHcUxsPBI3VE4A9X7U9zODoiHM1uFN0HV64U2oEKVsoBQgZ8Oz
    I2guFbp6nWC2eBWnW2Jvu4+PUB8PUiK4mE2XRFErb0va2XgzQuQXpeDM4jnaYdou
    BHdVUWtc0HITmnw/iv1YRFN70V+CL6crplMgwzLryd08IL/jjJRMMoJjSoEZxfuM
    6QrI7rCOisssRuRNd7WyaLs40rPeo2e27WfI5wx/xKf/Y3/nILZjKKnsbN2q9kC5
    j633VOB6dlRsiIEDedsJkPw+ZAT5L3ohAoIBAFOKWlMFudQ1u+jVnJwvRo3HSrEE
    Iw3zwnqB3CloEYyNW1NBythdWA/EH90n70nnugaN0pUpPEvdERxqubuu4ObquX2h
    gEGxMO3DKtPNSztKB/45ozvqJjM+DKPWhZElGkyrDx8T0jvySh+JBHMRalTQrQuA
    DNyGnGWFazk1uzTMuBoCOudCECC2cPqgkudmJigUXro+rf/QB4nEAE6K4KwWF7Pe
    K/oi2M1LpT/Sv6X3O5FXaok1N9jrhJcGDU0UebZaMDjvyAGdSqdXKZJh6Y7TLg2S
    m/6bWiwsHwTfrptzBeqiz1mihgVzLNiqep7iykq+xziKR18idk+JWRn8x4I=
    -----END RSA PRIVATE KEY-----
  identity.pub: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC30DYuJoDsE5bVK5y1rZonlEfR/PQsOAvkb4lHnBFCH0UJaF++69nivC1zf3YEMUuURl19BZm9L0MGvwaCpMTNquSydmm8VjK6zOdP32CuymQA6zaoMWU6GkwJU4dGNdUWLSApeOcgn2YquUnNfdfCwz9M5I2Eir8cW83sok2acQPEf2NXfmNRkbYo7NqZd+ze4ru0a7fRlEFhzI3iKcUWOQHizFvh6OhTYDLBwnA9nucwJEPYa8BdeIcQvm/gVGW9PhG/E/KN9zxzAzK4AyN+m4gaz8kJZHprck7vGwDvgN6ejVOLnwdr7ZQbBa3xm8jku2i8e7PAflV/C3/BnB9PsFGAZ5ISerBqWYjidqv5L5WHUSwTE4j/svK90jEA9iBBIgHhlc1TZ+jWRquOznOTP7KrE9xhFG/niOTudEf6PHUqo/T5QJSkYtrAyIIb+y5UbW1m8EfNH5C1ShFpFei9ILYfUOsgsoFBCr0UqAXUXijkmcpvJ7NLHq5AgenWKt0KUgGjOgHfWOoq1334z2my4065x4LR0SJgwZkJG8D6U4P+M2IPjRhGAswUmYfW44mn1o8R75m2HDtHOPuQnQJnviaabnQMpI8/whC/SDzwpFb9srz1wHfq03QFDJ3jkxiyJdz/3cjodu8aFqMmr5wGW+PRA/UGrGb3txrCwpZXyQ==
  known_hosts: |
    github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
