---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gitops-repo
  namespace: flux-system
spec:
  interval: 15s
  ref:
    branch: master
  secretRef:
    name: gitops-repo
  url: ssh://git@github.com/eruclstar/k8s-stack
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gitops-repo
  namespace: flux-system
spec:
  interval: 24h0m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-repo
  validation: client
